artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion

  # Local dataset path
  source_URL: dataset/brain_tumor_dataset.zip

  # Dataset copied into artifacts
  local_data_file: artifacts/data_ingestion/data.zip

  # Extracted dataset
  unzip_dir: artifacts/data_ingestion

data_transformation:
  root_dir: artifacts/data_transformation

  train_dir: artifacts/data_ingestion/Training

  test_dir: artifacts/data_ingestion/Testing

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion
  expected_classes:
    - glioma
    - meningioma
    - pituitary
    - notumor
  allowed_extensions:
    - .jpg
    - .jpeg
    - .png

prepare_base_model:
  root_dir: artifacts/prepare_base_model

  model_path: artifacts/prepare_base_model/base_model.keras

prepare_callbacks:
  root_dir: artifacts/prepare_callbacks

  checkpoint_model_filepath: artifacts/prepare_callbacks/model.keras

  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_logs
model_training:
  root_dir: artifacts/model_training

  trained_model_path: artifacts/model_training/model.keras

model_evaluation:
  root_dir: artifacts/model_evaluation

  model_path: artifacts/prepare_callbacks/model.keras

  evaluation_file_path: artifacts/model_evaluation/evaluation.json

  target_names:
    - Glioma
    - Meningioma
    - No Tumor
    - Pituitary

model_prediction:
  root_dir: artifacts/model_prediction

  model_path: artifacts/prepare_callbacks/model.keras

  image_size: [224, 224]

  class_names:
    - Glioma
    - Meningioma
    - No Tumor
    - Pituitary
